version: '3'
services:
  backend-web-server:
    image: backend-web-server
    build:
      context: ./server/
      dockerfile: Dockerfile
    volumes:
      - ./server:/server
    ports:
      - "8080:8080"
    working_dir: /server
    command: go run main.go
    environment:
      - AIRFLOW_HOST=192.168.1.59
      - AIRFLOW_PORT=8080
      - KAFKA_HOST=192.168.1.64
      - KAFKA_REST_PORT=8082
      - KAFKA_CONNECTORS_PORT=8083

  frontend-web-client:
    image: frontend-web-client
    build:
      context: ./client/
      dockerfile: Dockerfile
    volumes:
      - ./client:/client
    ports:
      - "80:3000"
    working_dir: /client
    command: npm start
    links:
      - backend-web-server