FROM arm64v8/golang:latest

# Add Maintainer Info
LABEL maintainer="Tom Tupy <tomtupy@gmail.com>"

# Set the Current Working Directory inside the container
WORKDIR /

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Build the Go app
RUN go get -u github.com/gorilla/mux
RUN go build -o main .

# Expose port 8080 to the outside world
EXPOSE 8080

# Command to run the executable
CMD ["./main"]